name: Retrieve GFF3 Paths from Ensembl RR

on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  retrieve-gff3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
        
      - name: Make script executable
        run: chmod +x ./scripts/ensembl_rapid_release.sh

      - name: Run script to retrieve GFF3 paths
        run: ./scripts/ensembl_rapid_release.sh

      - name: Map GFF3 paths to TSV file
        run: |
          awk -F'/' '{
            accession = $3;
            https_path = "https://ftp.ensembl.org/pub/rapid-release/species" substr($0, 2);
            print accession "\t" https_path
          }' gff3_paths.txt > ensembl_rapid_release.tsv

      - name: Remove txt file
        run: |
          rm gff3_paths.txt
          
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
